@startuml
|客户|
start
:在销售平台下单;

|订单履约系统|
:接收订单;
:收集和确认订单信息;
note right
包括客户详情、商品信息、
配送地址等
end note

:订单拆单;
note right
根据商品的仓储位置或
特定的履约要求进行拆分
end note

:派单;
note right
基于库存位置、配送距离、
履约能力等因素进行决策
end note

:预占库存;
:改派(如有需要);
note right
库存不足、配送问题或其他
突发情况可能导致改派
end note

|仓库/门店|
:拣货;
note right
根据订单信息从库存中
挑选出具体商品
end note

:打包;
note right
商品打包，贴上运输标签，
确保运输安全和完整
end note

:出库;
:记录为出库状态，商品发货;

|订单履约系统|
:物流配送;
note right
通过快递或同城配配送商品
end note

|客户|
:确认收货;
:订单履约完成;
note right
记录履约时效、收集反馈、
提升服务质量
end note

stop
@enduml
